/* Genere par tools/build-assets.ts depuis images/logo_club/. Ne pas modifier a la main. */

export interface EntreeClub {
  readonly id: string;
  readonly libelle: string;
  readonly fichier: string;
  readonly largeur: number;
  readonly hauteur: number;
  readonly alias: readonly string[];
}

export const CLUBS = {
  '4s': {
    id: '4s',
    libelle: '4S',
    fichier: '4s.png',
    largeur: 225,
    hauteur: 225,
    alias: [],
  },
  'bourges': {
    id: 'bourges',
    libelle: 'Bourges',
    fichier: 'bourges.png',
    largeur: 256,
    hauteur: 156,
    alias: [],
  },
  'chailles': {
    id: 'chailles',
    libelle: 'Chailles',
    fichier: 'chailles.png',
    largeur: 150,
    hauteur: 150,
    alias: ['chailles-tt'],
  },
  'st-avertin': {
    id: 'st-avertin',
    libelle: 'St Avertin',
    fichier: 'st-avertin.png',
    largeur: 185,
    hauteur: 80,
    alias: ['st-avertin-tt', 'saint-avertin'],
  },
  'st-laurent': {
    id: 'st-laurent',
    libelle: 'St Laurent',
    fichier: 'st-laurent.png',
    largeur: 225,
    hauteur: 225,
    alias: ['st-laurent-tt', 'saint-laurent'],
  },
  'ac-amboise': {
    id: 'ac-amboise',
    libelle: 'AC Amboise',
    fichier: 'ac-amboise.png',
    largeur: 195,
    hauteur: 194,
    alias: ['amboise'],
  },
  'amo-mer-tt': {
    id: 'amo-mer-tt',
    libelle: 'AMO Mer TT',
    fichier: 'amo-mer-tt.png',
    largeur: 187,
    hauteur: 222,
    alias: ['amo-mer', 'mer-tt'],
  },
  'asj-la-chaussee-st-victor': {
    id: 'asj-la-chaussee-st-victor',
    libelle: 'ASJ La Chaussée St Victor',
    fichier: 'asj-la-chaussee-st-victor.png',
    largeur: 211,
    hauteur: 197,
    alias: ['la-chaussee-st-victor-tt', 'la-chaussee-st-victor', 'asj-la-chaussee-st-victor-tt', 'la-chaussee'],
  },
  'ass-clery-st-andre': {
    id: 'ass-clery-st-andre',
    libelle: 'ASS Cléry St André',
    fichier: 'ass-clery-st-andre.png',
    largeur: 256,
    hauteur: 250,
    alias: ['clery-st-andre', 'clery'],
  },
  'aze-tt': {
    id: 'aze-tt',
    libelle: 'Azé TT',
    fichier: 'aze-tt.png',
    largeur: 207,
    hauteur: 202,
    alias: ['aze'],
  },
  'berri-chateauroux': {
    id: 'berri-chateauroux',
    libelle: 'Berri Châteauroux',
    fichier: 'berri-chateauroux.png',
    largeur: 225,
    hauteur: 224,
    alias: ['chateauroux', 'berri'],
  },
  'blois-ping-41': {
    id: 'blois-ping-41',
    libelle: 'Blois Ping 41',
    fichier: 'blois-ping-41.png',
    largeur: 234,
    hauteur: 215,
    alias: ['blois-ping', 'blois'],
  },
  'chateauneuf': {
    id: 'chateauneuf',
    libelle: 'Châteauneuf',
    fichier: 'chateauneuf.png',
    largeur: 225,
    hauteur: 225,
    alias: ['chateauneuf-tt'],
  },
  'cmp-jm-ingre-tt': {
    id: 'cmp-jm-ingre-tt',
    libelle: 'CMP JM Ingré TT',
    fichier: 'cmp-jm-ingre-tt.png',
    largeur: 215,
    hauteur: 256,
    alias: ['ingre-tt', 'ingre', 'cmp-jm-ingre'],
  },
  'ctt-ouchamps': {
    id: 'ctt-ouchamps',
    libelle: 'CTT Ouchamps',
    fichier: 'ctt-ouchamps.png',
    largeur: 203,
    hauteur: 182,
    alias: ['ouchamps'],
  },
  'ent-martizay-buzancais': {
    id: 'ent-martizay-buzancais',
    libelle: 'Ent. Martizay Buzançais',
    fichier: 'ent-martizay-buzancais.png',
    largeur: 256,
    hauteur: 255,
    alias: ['martizay-buzancais', 'martizay', 'buzancais'],
  },
  'es-maintenon-pierres': {
    id: 'es-maintenon-pierres',
    libelle: 'ES Maintenon Pierres',
    fichier: 'es-maintenon-pierres.png',
    largeur: 256,
    hauteur: 256,
    alias: ['maintenon-pierres', 'maintenon'],
  },
  'es-mulsans': {
    id: 'es-mulsans',
    libelle: 'ES Mulsans',
    fichier: 'es-mulsans.png',
    largeur: 256,
    hauteur: 63,
    alias: ['mulsans'],
  },
  'esc-cour-cheverny-tt': {
    id: 'esc-cour-cheverny-tt',
    libelle: 'ESC Cour Cheverny TT',
    fichier: 'esc-cour-cheverny-tt.png',
    largeur: 180,
    hauteur: 103,
    alias: ['cour-cheverny-tt', 'cour-cheverny', 'esc-cour-cheverny'],
  },
  'fl-st-aignan': {
    id: 'fl-st-aignan',
    libelle: 'FL St Aignan',
    fichier: 'fl-st-aignan.png',
    largeur: 225,
    hauteur: 173,
    alias: ['st-aignan'],
  },
  'fr-parassy-tt': {
    id: 'fr-parassy-tt',
    libelle: 'FR Parassy TT',
    fichier: 'fr-parassy-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['parassy-tt', 'parassy'],
  },
  'gien-as-tt': {
    id: 'gien-as-tt',
    libelle: 'Gien AS TT',
    fichier: 'gien-as-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['gien', 'as-gien-tt'],
  },
  'laigle-sellois-tt': {
    id: 'laigle-sellois-tt',
    libelle: 'L\'aigle Sellois TT',
    fichier: 'laigle-sellois-tt.png',
    largeur: 159,
    hauteur: 160,
    alias: ['aigle-sellois-tt', 'aigle-sellois', 'laigle-sellois'],
  },
  'mont-pres-chambord': {
    id: 'mont-pres-chambord',
    libelle: 'Mont-près-Chambord',
    fichier: 'mont-pres-chambord.png',
    largeur: 256,
    hauteur: 92,
    alias: ['montpreschambord', 'mont-pres-chambord-tt'],
  },
  'neuville-sports': {
    id: 'neuville-sports',
    libelle: 'Neuville Sports',
    fichier: 'neuville-sports.png',
    largeur: 255,
    hauteur: 256,
    alias: ['neuville'],
  },
  'orleans': {
    id: 'orleans',
    libelle: 'Orléans',
    fichier: 'orleans.png',
    largeur: 256,
    hauteur: 246,
    alias: ['orleans-tt'],
  },
  'ping-sassay-loisirs': {
    id: 'ping-sassay-loisirs',
    libelle: 'Ping Sassay Loisirs',
    fichier: 'ping-sassay-loisirs.png',
    largeur: 171,
    hauteur: 127,
    alias: ['sassay'],
  },
  'pong-vendomois': {
    id: 'pong-vendomois',
    libelle: 'Pong Vendômois',
    fichier: 'pong-vendomois.png',
    largeur: 256,
    hauteur: 221,
    alias: ['vendome', 'pong-vendomois-tt'],
  },
  'pp-st-georgescher': {
    id: 'pp-st-georgescher',
    libelle: 'PP St Georges/Cher',
    fichier: 'pp-st-georgescher.png',
    largeur: 256,
    hauteur: 198,
    alias: ['ppc-st-georges', 'pp-st-georges', 'st-georgescher', 'ppc-st-georgescher'],
  },
  'salbris-sologne-tt': {
    id: 'salbris-sologne-tt',
    libelle: 'Salbris Sologne TT',
    fichier: 'salbris-sologne-tt.png',
    largeur: 186,
    hauteur: 185,
    alias: ['salbris'],
  },
  'sc-moree-tt': {
    id: 'sc-moree-tt',
    libelle: 'SC Morée TT',
    fichier: 'sc-moree-tt.png',
    largeur: 191,
    hauteur: 180,
    alias: ['moree', 'moree-tt'],
  },
  'st-marceau-orleans-tt': {
    id: 'st-marceau-orleans-tt',
    libelle: 'St Marceau Orléans TT',
    fichier: 'st-marceau-orleans-tt.png',
    largeur: 189,
    hauteur: 194,
    alias: ['st-marceau', 'st-marceau-orleans'],
  },
  'st-sulpice-tt': {
    id: 'st-sulpice-tt',
    libelle: 'St Sulpice TT',
    fichier: 'st-sulpice-tt.png',
    largeur: 254,
    hauteur: 256,
    alias: ['st-sulpice', 'saint-sulpice-tt'],
  },
  'sud-loire-tt-45': {
    id: 'sud-loire-tt-45',
    libelle: 'Sud Loire TT 45',
    fichier: 'sud-loire-tt-45.png',
    largeur: 256,
    hauteur: 139,
    alias: ['sud-loire-tt', 'sud-loire'],
  },
  'tt-aubigny-sure-nere': {
    id: 'tt-aubigny-sure-nere',
    libelle: 'TT Aubigny-sur-Nère',
    fichier: 'tt-aubigny-sure-nere.png',
    largeur: 256,
    hauteur: 256,
    alias: ['tt-aubigny-sur-nere', 'aubigny-sur-nere', 'aubigny'],
  },
  'tt-germinois': {
    id: 'tt-germinois',
    libelle: 'TT Germinois',
    fichier: 'tt-germinois.png',
    largeur: 256,
    hauteur: 178,
    alias: ['germinois'],
  },
  'us-chouzy-tt': {
    id: 'us-chouzy-tt',
    libelle: 'US Chouzy TT',
    fichier: 'us-chouzy-tt.png',
    largeur: 217,
    hauteur: 216,
    alias: ['chouzy', 'chouzy-tt'],
  },
  'usm-olivet-tt': {
    id: 'usm-olivet-tt',
    libelle: 'USM Olivet TT',
    fichier: 'usm-olivet-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['usm-olivet', 'olivet'],
  },
  'vierzon': {
    id: 'vierzon',
    libelle: 'Vierzon',
    fichier: 'vierzon.png',
    largeur: 193,
    hauteur: 246,
    alias: ['vierzon-tt'],
  },
  'villefranchecher-tt': {
    id: 'villefranchecher-tt',
    libelle: 'Villefranche/Cher TT',
    fichier: 'villefranchecher-tt.png',
    largeur: 214,
    hauteur: 213,
    alias: ['villefranche-tt', 'villefranche', 'villefranchecher'],
  },
  'villerbon-tt': {
    id: 'villerbon-tt',
    libelle: 'Villerbon TT',
    fichier: 'villerbon-tt.png',
    largeur: 226,
    hauteur: 222,
    alias: ['villerbon'],
  },
  'vineuil-suevres-tt': {
    id: 'vineuil-suevres-tt',
    libelle: 'Vineuil Suèvres TT',
    fichier: 'vineuil-suevres-tt.png',
    largeur: 256,
    hauteur: 125,
    alias: ['vineuil-suevres', 'vineuil', 'vs-tt'],
  },
} as const satisfies Record<string, EntreeClub>;

/** Identifiant litteral : referencer un club inexistant ne compile pas. */
export type ClubId = keyof typeof CLUBS;
