/* Genere par tools/build-assets.ts depuis images/logo_club/. Ne pas modifier a la main. */

export interface EntreeClub {
  readonly id: string;
  readonly libelle: string;
  readonly fichier: string;
  readonly largeur: number;
  readonly hauteur: number;
  readonly alias: readonly string[];
}

export const CLUBS = {
  '4s': {
    id: '4s',
    libelle: '4S',
    fichier: '4s.png',
    largeur: 256,
    hauteur: 256,
    alias: [],
  },
  bourges: {
    id: 'bourges',
    libelle: 'Bourges',
    fichier: 'bourges.png',
    largeur: 256,
    hauteur: 256,
    alias: [],
  },
  chailles: {
    id: 'chailles',
    libelle: 'Chailles',
    fichier: 'chailles.png',
    largeur: 256,
    hauteur: 256,
    alias: ['chailles-tt'],
  },
  'st-avertin': {
    id: 'st-avertin',
    libelle: 'St Avertin',
    fichier: 'st-avertin.png',
    largeur: 256,
    hauteur: 256,
    alias: ['st-avertin-tt', 'saint-avertin'],
  },
  'st-laurent': {
    id: 'st-laurent',
    libelle: 'St Laurent',
    fichier: 'st-laurent.png',
    largeur: 256,
    hauteur: 256,
    alias: ['st-laurent-tt', 'saint-laurent'],
  },
  'ac-amboise': {
    id: 'ac-amboise',
    libelle: 'AC Amboise',
    fichier: 'ac-amboise.png',
    largeur: 256,
    hauteur: 256,
    alias: ['amboise'],
  },
  'amo-mer-tt': {
    id: 'amo-mer-tt',
    libelle: 'AMO Mer TT',
    fichier: 'amo-mer-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['amo-mer', 'mer-tt'],
  },
  'asj-la-chaussee-st-victor': {
    id: 'asj-la-chaussee-st-victor',
    libelle: 'ASJ La Chaussée St Victor',
    fichier: 'asj-la-chaussee-st-victor.png',
    largeur: 256,
    hauteur: 256,
    alias: [
      'la-chaussee-st-victor-tt',
      'la-chaussee-st-victor',
      'asj-la-chaussee-st-victor-tt',
      'la-chaussee',
    ],
  },
  'aze-tt': {
    id: 'aze-tt',
    libelle: 'Azé TT',
    fichier: 'aze-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['aze'],
  },
  'blois-ping-41': {
    id: 'blois-ping-41',
    libelle: 'Blois Ping 41',
    fichier: 'blois-ping-41.png',
    largeur: 256,
    hauteur: 256,
    alias: ['blois-ping', 'blois'],
  },
  chateauneuf: {
    id: 'chateauneuf',
    libelle: 'Châteauneuf',
    fichier: 'chateauneuf.png',
    largeur: 256,
    hauteur: 256,
    alias: ['chateauneuf-tt'],
  },
  'cmp-jm-ingre-tt': {
    id: 'cmp-jm-ingre-tt',
    libelle: 'CMP JM Ingré TT',
    fichier: 'cmp-jm-ingre-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['ingre-tt', 'ingre', 'cmp-jm-ingre'],
  },
  'ctt-ouchamps': {
    id: 'ctt-ouchamps',
    libelle: 'CTT Ouchamps',
    fichier: 'ctt-ouchamps.png',
    largeur: 256,
    hauteur: 256,
    alias: ['ouchamps'],
  },
  'es-mulsans': {
    id: 'es-mulsans',
    libelle: 'ES Mulsans',
    fichier: 'es-mulsans.png',
    largeur: 256,
    hauteur: 256,
    alias: ['mulsans'],
  },
  'esc-cour-cheverny-tt': {
    id: 'esc-cour-cheverny-tt',
    libelle: 'ESC Cour Cheverny TT',
    fichier: 'esc-cour-cheverny-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['cour-cheverny-tt', 'cour-cheverny', 'esc-cour-cheverny'],
  },
  'fl-st-aignan': {
    id: 'fl-st-aignan',
    libelle: 'FL St Aignan',
    fichier: 'fl-st-aignan.png',
    largeur: 256,
    hauteur: 256,
    alias: ['st-aignan'],
  },
  'gien-as-tt': {
    id: 'gien-as-tt',
    libelle: 'Gien AS TT',
    fichier: 'gien-as-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['gien', 'as-gien-tt'],
  },
  'laigle-sellois-tt': {
    id: 'laigle-sellois-tt',
    libelle: "L'aigle Sellois TT",
    fichier: 'laigle-sellois-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['aigle-sellois-tt', 'aigle-sellois', 'laigle-sellois'],
  },
  'mont-pres-chambord': {
    id: 'mont-pres-chambord',
    libelle: 'Mont-près-Chambord',
    fichier: 'mont-pres-chambord.png',
    largeur: 256,
    hauteur: 256,
    alias: ['montpreschambord', 'mont-pres-chambord-tt'],
  },
  orleans: {
    id: 'orleans',
    libelle: 'Orléans',
    fichier: 'orleans.png',
    largeur: 256,
    hauteur: 256,
    alias: ['orleans-tt'],
  },
  'ping-sassay-loisirs': {
    id: 'ping-sassay-loisirs',
    libelle: 'Ping Sassay Loisirs',
    fichier: 'ping-sassay-loisirs.png',
    largeur: 256,
    hauteur: 256,
    alias: ['sassay'],
  },
  'pong-vendomois': {
    id: 'pong-vendomois',
    libelle: 'Pong Vendômois',
    fichier: 'pong-vendomois.png',
    largeur: 256,
    hauteur: 256,
    alias: ['vendome', 'pong-vendomois-tt'],
  },
  'pp-st-georgescher': {
    id: 'pp-st-georgescher',
    libelle: 'PP St Georges/Cher',
    fichier: 'pp-st-georgescher.png',
    largeur: 256,
    hauteur: 256,
    alias: ['ppc-st-georges', 'pp-st-georges', 'st-georgescher', 'ppc-st-georgescher'],
  },
  'salbris-sologne-tt': {
    id: 'salbris-sologne-tt',
    libelle: 'Salbris Sologne TT',
    fichier: 'salbris-sologne-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['salbris'],
  },
  'sc-moree-tt': {
    id: 'sc-moree-tt',
    libelle: 'SC Morée TT',
    fichier: 'sc-moree-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['moree', 'moree-tt'],
  },
  'st-marceau-orleans-tt': {
    id: 'st-marceau-orleans-tt',
    libelle: 'St Marceau Orléans TT',
    fichier: 'st-marceau-orleans-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['st-marceau', 'st-marceau-orleans'],
  },
  'st-sulpice-tt': {
    id: 'st-sulpice-tt',
    libelle: 'St Sulpice TT',
    fichier: 'st-sulpice-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['st-sulpice', 'saint-sulpice-tt'],
  },
  'sud-loire-tt-45': {
    id: 'sud-loire-tt-45',
    libelle: 'Sud Loire TT 45',
    fichier: 'sud-loire-tt-45.png',
    largeur: 256,
    hauteur: 256,
    alias: ['sud-loire-tt', 'sud-loire'],
  },
  'us-chouzy-tt': {
    id: 'us-chouzy-tt',
    libelle: 'US Chouzy TT',
    fichier: 'us-chouzy-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['chouzy', 'chouzy-tt'],
  },
  vierzon: {
    id: 'vierzon',
    libelle: 'Vierzon',
    fichier: 'vierzon.png',
    largeur: 256,
    hauteur: 256,
    alias: ['vierzon-tt'],
  },
  'villefranchecher-tt': {
    id: 'villefranchecher-tt',
    libelle: 'Villefranche/Cher TT',
    fichier: 'villefranchecher-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['villefranche-tt', 'villefranche', 'villefranchecher'],
  },
  'villerbon-tt': {
    id: 'villerbon-tt',
    libelle: 'Villerbon TT',
    fichier: 'villerbon-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['villerbon'],
  },
  'vineuil-suevres-tt': {
    id: 'vineuil-suevres-tt',
    libelle: 'Vineuil Suèvres TT',
    fichier: 'vineuil-suevres-tt.png',
    largeur: 256,
    hauteur: 256,
    alias: ['vineuil-suevres', 'vineuil', 'vs-tt'],
  },
} as const satisfies Record<string, EntreeClub>;

/** Identifiant litteral : referencer un club inexistant ne compile pas. */
export type ClubId = keyof typeof CLUBS;
